version: '2'
services:
  db:
    image: mysql:5.7.11
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=passwd
      - MYSQL_USER=root
      - MYSQL_PASSWORD=facturascripts
      - MYSQL_DATABASE=facturascripts
  app:
    image: facturascripts
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html/
    depends_on:
      - db
    links:
      - db
    environment:
      - MYSQL_SERVER=db
      - MYSQL_PASSWORD=facturascripts
      - MYSQL_USER=root
